name: @name@
description: /sell command that allows you to put things into GUI and then sell them by closing
version: @version@
author: xHyroM
main: dev.xhyrom.peddlerspocket.PeddlersPocket
api-version: 1.17